providers:
  sendgrid:
    api_token: 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
  sendinblue:
    api_token: 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
default_provider: sendinblue
referrer_whitelist:
- juncture-digital.org
- dev.juncture-digital.org
- localhost:8080
- kent-maps.online
- dofe.kent-maps.online
- lab.plant-humanities.org
